"""empty message

Revision ID: 9981012aee39
Revises: 4a7e19d182f2
Create Date: 2020-01-20 06:49:47.067390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9981012aee39'
down_revision = '4a7e19d182f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = FALSE WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
